# Biobasis Daily Met Merge Configuration
# Minimal config for merging daily meteorological data files

# Input directory containing Biobasis_MM1_YYYYMMDD.dat files
input_dir: "tests/data"

# Output directory for merged files
output_dir: "data/output"

# Date range (YYYYMMDD format or ISO format YYYY-MM-DD)
date_start: "20240101"
date_end: "20240103"
