# Biobasis Merge Configuration - R version

# Input and output directories (relative to R/R/ directory)
input_dir: "../../tests/data"
output_dir: "../../data/output"

# Date range (YYYYMMDD format)
date_start: "20240101"
date_end: "20240103"

# File naming convention
file_prefix: "Biobasis"
station_id: "MM1"

# Logging
log_level: "INFO"

# Output format options
output_formats:
  parquet: true
  csv_gz: true
  metadata: true
  plots: true
